<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>
<div id="wrapper" class="index-wrapper">
    <div class="container">
        <h2 class="blog-heading ">Diwali Decoration Tips to Decorate your Home Like a Paradise</h2>
        <div class="row" style="place-content:center; padding: 0 15px;">
            <img src="<?php echo base_url(); ?>assets/img/user-blog-14.jpg" class="blogs-logo">
        </div>
        <div class="blog-2-headinng-content">
            <p>It is that time of the year again! When the colourfully adorned streets are topped with flashy colourful strings strung closely to cover the entire streets and markets as they spread glitter like joy among the busy and fussy shoppers, the vivid sight of sparkly light strings and webs to which vendors on the streets constantly grab your attention with the best bargains, rangoli colour vendors making rangoli designs on the street-side as they demonstrate the catchiest designs of their rangoli stencil collections while competing who&rsquo;s got the best collection, the variety of colourful and vibrant diyas and candles in various shapes and sizes, matching the aesthetic vibes of all the customers from modern to traditional. It&rsquo;s that time again, it is the festival time, it is Diwali time!</p>
            <p>Since childhood, all of us waited months for this time of the year for all the excitement among our play groups, in hustle and bustle of super busy and clamouring market places. Every year, all aunties engaged into a self-imposed subtle competition of whose rangoli is the biggest and the brightest and which house sparkle the best of all as kids went prancing about these beautiful embellishments all streets sparkling as if stars have been momentarily borrowed from the sky for Diwali decorations. The delight of putting up colourful house lights strung into big and beautiful webs or neatly stacked rows and turning them on in the evening for weeks and neighbourhood aunties discussing whose house shines the brightest from the Diwali cleaning efforts of months.</p>
            <p>Such is the craze of the festive season in India, such is the craze of Diwali in India! However, due to the Covid-19 pandemic with strict social distancing requirements set in place, it has become cumbersome to freely shop around here and there, packing our trunks with the festive collections. Numerous small vendors and sellers and many people from various economic backgrounds also lost their livelihoods in the pandemic and hence began making and selling home-made d&eacute;cor products packed with love into the markets. At Gharobaar, we bring to you these lovely festive d&eacute;cor collections packed with love from the homes of our producers to yours and hence, go #govocalforlocal!</p>
            <p>&nbsp;</p>
            <p><strong>Choose from our wide range of product listings below:</strong></p>
            <ol>
                <li>Does an Indian festival even feel like a festival without bright and beautiful colours? NOT AT ALL! Walking past the streets, almost every house is adorned with bright and <a href="https://www.gharobaar.com/iktaara-rangoli-the-holy-feet-ready-rangoli-pack-2482" class="links-in-blogs">beautiful rangolis</a>, some containing traditional patterns and others with minimalistic and beautiful designs. Some as big as covering almost entire entrances, some neatly wrapped around corners like garlands for the house doors. Rangoli is a must for Diwali d&eacute;cor. It is almost always the first thing for d&eacute;cor that comes to mind for Diwali, adorned with beautiful candles and diyas that further highlight the vivid colours.</li>
                <li>On our visits to our friends and relatives and even around the marketplace, beautiful vertical strings of beads and mirrors are almost inevitable. Bright mirrors reflecting the lights around and the scintillating beads sparkle up the entire rooms along with hallways and galleries.</li>
                <li>Many of us love being creative with the d&eacute;cor ideas for Diwali. An excellent DIY with a subtle traditional touch can be using a copper vessel. By filling in it some water, just by adding some sprinkles and flowers to it, we can get the perfect pooja d&eacute;cor that goes with almost any interior setting, traditional or modern.</li>
                <li><a href="https://www.gharobaar.com/products?search=scented%20candles" class="links-in-blogs">Scented candles</a> in various shapes and sizes make for wonderful d&eacute;cor ornaments. They can either be placed in beautiful vessels full of water and flowers, with rangoli or simply lit around the house in balconies as well as in the living room areas. With the aroma and cleansing properties, scented candles make the perfect option besides releasing stress and boosting mood.</li>
                <li>When it is the festive season, every room in all of our homes are adorned with new bedcovers and pillow covers. <a href="https://www.gharobaar.com/home-accents/wall-decor-hangings" class="links-in-blogs">Pillow covers</a> are an important part of d&eacute;cor right from bedrooms to drawing rooms and living rooms. Bright colours matching the festive sparkles make an ideal choice.</li>
                <li>Little table organizers for either putting in some vegetables or stationary items help keep the surroundings neat and tidy, while adding an aesthetic edge to the d&eacute;cor. Beautiful bowls and vessels can be used for the same.</li>
                <li>Picture frames are a very intimate part of our d&eacute;cor that is full of emotions. Putting bright and beautiful frames here and there adds a nostalgic touch to our homes that we hold dearly to our hearts.</li>
                <li>New lampshades or DIY redecoration for the old ones can brings a whole different vibe to our homes by dazzling up our living and bedrooms with different shades of lights.</li>
                <li><a href="https://www.gharobaar.com/products?search=lantern" class="links-in-blogs">Lanterns</a> are yet another way to jazz up the vibrant d&eacute;cor in our homes. During the festive season, lanterns big and bright, all beautiful are available in various shapes and sizes. We can put up lanterns as an addition to our balconies or living rooms.</li>
                <li>Bowls and vessels for filling in with water, flowers or candles make excellent accessories for decorating homes.</li>
            </ol>
        </div>
    </div>
</div>