<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>

<div id="wrapper" class="index-wrapper">
    <div class="container">
        <h2 class="blog-heading ">Reasons to Say Yes to Handmade Products</h2>
        <div class="row" style="place-content:center; padding: 0 15px;">
            <img src="<?php echo base_url(); ?>assets/img/user-blog-9.jpg" class="blogs-logo">
        </div>

        <p class="blog-sub-heading"><strong>Background:</strong></p>
        <div class="blog-2-headinng-content">
            <p>When it comes to art, no machine or technology can match the creativity and magic of the human hand. God has given human beings, some special power to create wonderful things, which man has not been able to pass on to machines. No wonder, even in this age of technology, handmade products, and handmade crafts have retained their charm.</p>
            <p>Though handmade products take more time as compared to products made using machines, and are often more expensive also, there are several reasons why people prefer handmade crafts over machine-made products. Some of the reasons are listed below:</p>
            <ol>
                <li><strong> Connection with history: </strong>Before the industrial revolution, all products were made in homes, or small units called cottage industries. It was only after the Industrial Revolution, the machines were introduced for mass production. And the handmade products and handmade crafts became a part of history. So, when we see anything that&rsquo;s handmade, it reminds us of history.</li>
                <li><strong> Top quality products: </strong>Try sipping a coffee that&rsquo;s hand-brewed and then try a coffee that brewed in the machine. You will feel the difference, and you would realize the magic of human hands. The same holds true for handmade crafts as well. The hand-made products consume less of energy and more of artisan skill and passion for his/her creation. This is what makes handmade products more durable and sustainable as compared to products produced in an assembly line.</li>
                <li><strong> Easily Customizable: </strong>The handmade products are made by artists which showcase his love and passion for his creation. So, all handmade crafts are pure, unique, and carry the signature style of the artist. And that&rsquo;s not all; these handmade products can easily be customized. And in case you are planning to gift it to someone, you can personalize it as well with the name of the receiver. It ensures that someone else has a similar product is very minimal. This creates an emotional connection with the gift.</li>
                <li><strong> Environment Friendly:</strong> The handmade products are made using less of skill and natural resources. Also, most handmade crafts are made using biodegradable materials; hence do not contribute to adding carbon to the atmosphere. Also, since handmade crafts involve using materials, which are available locally, they involve little or no fuel consumption in transportation.</li>
                <li><strong> Contributes to the economic growth of the local community: </strong>The handmade crafts have traditionally been made in the homes, by the local artists, using the raw material, which is easily available in their vicinity. As the sale of these handmade products goes up, the artists and their suppliers get more business. And, if these handmade products are exported, they help the country get invaluable foreign exchange as well, thereby helping the local community and Indian economy as well.</li>
                <li><strong> Supporting the unsung talent: </strong>Most of the time, the handmade craft is made by artists, who are not known, and who are struggling to make both ends meet and preserve the traditional art. So, buying handmade products ensures that these unsung artists are able to earn a decent livelihood and ensure that the art does not die. So, when you pick up a handmade craft, you are silently and unknowingly promoting an unsung talent and helping these talented, but unsung artists get global exposure. This brings a smile to their faces as well and is a definite feel-good factor for everyone.</li>
                <li><strong> Unique and Trendy: </strong>Since the handmade crafts are made without any involvement to machines, it's quite easy and quick to change the design and patterns to reflect the current trends. Depending upon the requirements the handmade products can be made funky, or functional while retaining originality.</li>
                <li><strong> Keeps the art alive: </strong>In this era of machine-produced goods, handmade crafts are like fresh air. Buying handmade products is like giving a message to probably the last generation of these dying art forms. A message that we are with you, and we respect your art and talent. The handmade crafts are a legacy of our culture and they showcase our cultural diversity. So, buying handmade craft is a clear signal to them that keeping this tradition alive is economically feasible as well so that they can prepare the next generation for keeping it alive.</li>
            </ol>

            <p><strong>Conclusion:</strong></p>
            <p>Gharobaar is one such platform, which allows you to see these handmade crafts, all in one place, so, now you can come to Gharobaar and select the handmade products and handmade crafts that you like. These products will not only improve the aesthetic value of your d&eacute;cor but also take you back in history in the modern era. These products are more durable and eco-friendly. Not only do they help bring a smile to the faces of the artisans, and them help run their families while preserving the art, it also helps the Indian economy.</p>
        </div>
    </div>
</div>