<?php defined('BASEPATH') or exit('No direct script access allowed'); ?>

<div id="wrapper" class="index-wrapper">
    <div class="container">
        <h2 class="blog-heading ">Why are Films Suddenly embracing everything ethnic?</h2>
        <div class="row" style="place-content:center; padding: 0 15px;">
            <img src="<?php echo base_url(); ?>assets/img/user-blog-11.jpg" class="blogs-logo">
        </div>

        <div class="blog-2-headinng-content">
            <p class="blog-sub-heading"><strong>Background:</strong></p>
            <p>In a country like India, where over 1000 movies are released every year, movies are not just a form of entertainment. It&rsquo;s much more than that. It&rsquo;s actually a reflection of the Indian society, and gets affected by the happenings in our society. Whatever we see in our society comes on the big screen. However, this relation is not one way. Many a times, it has been seen that that things that we see in movies are adopted by common people. The biggest impact of movies on our life is in terms of our dresses, and lifestyle.</p>
            <p class="blog-sub-heading"><strong>Impact of Cinema on our dresses:</strong></p>
            <p>The Hindi movie industry, popularly, termed &lsquo;Bollywood&rsquo; has singe ages had a big influence on our fashion sense. As soon as a movie becomes super hit, its characters, names, and dialogues become a part of the daily lingo. In addition to this, the dresses worn by the leading characters also become the talk of the town. This is very true especially for the ethnic wear like lehengas, suits and other Indian traditional wear. The tailors work day and night to create replicas of those outfits, which are quickly grabbed by the people as a new fashion trend. The demand for these dresses goes up and the mannequins can be seen adorning these dresses in every garment shop. To make the task easier, these ethnic wear and Indian traditional wear are named after the name of the movie, or the character. Some worthwhile mentions are the Anarkali suit (from the cult movie Mughal-a-Azam), the Jodha jewellery (from Jodha Akbar), and the &lsquo;Masakali Suit&rsquo; (from Delhi-6).</p>
            <p class="blog-sub-heading"><strong>Recent Trends:</strong></p>
            <p>Well, these examples were from past, but even if you look at the recent movies, the trend continues.</p>
            <p>With the change of the millennium, the fashion also changed on the silver screen. There was a time, when the western dresses were very popular in the movies. In the recent times, several film makers started a new trend of showing the leading lady in ethnic wear and Indian traditional wear as well. During the entire movie, she may wear western clothes, but when it comes to situations like weddings, or family function, she is shown wearing an Indian traditional wear, like lehengas or some other ethnic wear.</p>
            <p>And for this purposes, the filmmakers started hiring fashion designers with a clear brief to come up unique styles and classic designer pieces for ethnic wear. The Indian traditional wear, which are shown on the big screen, soon adorn all the shops in the market.</p>
            <p>Take for examples, recent movies like Badrinath ki Dulhaniya, and Padmavat. Both these movies showed the leading lady wearing the Indian traditional wear, like lehenga and other ethinc wear, like suits. Similarly, the much controversial movie, Padamavat, which was actually a period movie, went a step further. The movie not only showcased the traditional lehengas, but highlighted the grandeur of the royal family, in terms of jewellery, paintings, wall d&eacute;cor, wall hangings, and many other things. As soon as these movies were released, there was a sudden increase in the demand for the kind of lehengas worn by the leading lady.</p>
            <p class="blog-sub-heading"><strong>What makes these dresses special?</strong></p>
            <p>Many of the Indian film makers have used the big screen to actually show the grandness of the life. They have used movies to showcase the characters in &lsquo;larger-than-life&rsquo; avatar. And this is reflected in every they do, and everything they wear.</p>
            <p>All the dresses shown in the movies are designed by the top designers of the country. Every Indian aspires to wear dresses designed by top fashion makers like Manish Malhotra, Neeta Lulla, Ritu Beri and the likes. But the hard reality is that most people, in India, cannot afford to buy these dresses. So, when they see a dress in a movie, which is both attractive, and is designed by a top fashion designer, they find a cost-effective way to fulfill their desire.</p>
            <p>These dresses give the people a chance to actually see how a new style looks, and thus they are saved off the risk of trying something, which does not look good on them. You can visit any India wedding or a family get-together, and you can witnesses our female relative dressed as the beautiful Bollywood divas, dancing to the hit numbers from these movies.</p>
            <p class="blog-sub-heading"><strong>The d&eacute;cor: </strong></p>
            <p>Dresses are not the only thing that catches the attention of the movie goers. There are people, who apart from enjoying the movie, its songs and stories, pay lot of attention to the things around them &ndash; the curtains, the wall hangings, and the d&eacute;cor. And just like the dresses, these showpieces also see a transition from the movies to our homes.</p>
            <p class="blog-sub-heading"><strong>Conclusion:</strong></p>
            <p>So, you also excited to catch the latest trends of Bollywood, but don&rsquo;t know what&rsquo;s trending. Even if you know, what&rsquo;s in trend, but did not know, where to get that. Then, Gharobaar is the answer to all your questions. From the best of the lehengas to the other ethnic wear, and latest wall d&eacute;cor, you can find everything here.</p>
        </div>
    </div>
</div>